# Generated by Django 3.2 on 2023-09-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230916_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre_Title',
        ),
    ]
