# Generated by Django 3.2 on 2023-09-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230922_1938'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='year_lte_current_year',
        ),
        migrations.RemoveConstraint(
            model_name='title',
            name='year_gte_minimum_year',
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(check=models.Q(year__lte=2023), name='year_lte_this_year'),
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(check=models.Q(year__gte=1900), name='year_gte_min_year'),
        ),
    ]
